### ISSUE TITLE
clojure.pprint/pprint-table

### ISSUE THREAD

**Issue by bherrmann7** [cldwalker/table#3]
FYI: 
It isnt clojure.pprint/pprint-table

it is clojure.pprint/print-table

Cheers!

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 13 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/table#3). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by bherrmann7** [comment]
Yikes I see clojure has both pprint-table and print-table.  My bad.
